name: sna-ceb-assignment

channels:
  - defaults
  - conda-forge

dependencies:
  - python==3.10
  - conda-forge::python-dotenv==0.21.0
  - conda-forge::pyvis==0.3.1
  - conda-forge::networkx==3.1
  - conda-forge::matplotlib==3.8.0
  - conda-forge::numpy==1.26.2
  - conda-forge::pandas==2.1.
  - conda-forge::seaborn==0.13.0
  - conda-forge::jupyterlab==4.0.8
  - pip==20.2